In [1]:
# Scientific libraries
import numpy as np

#matplotlib notebook
import matplotlib.pyplot as plt

import astropy.io.fits as fits

import astropy.units as u
from astropy.coordinates import ICRS, Galactic, SkyCoord

from pyspi.spi_pointing import SPIPointing
from pyspi.spi_frame import SPIFrame

from pyspi.utils.geometry import cart2polar, polar2cart

/home/tsiegert/miniconda2/envs/threeML/lib/python2.7/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters

WARNING UserWarning: Using default configuration from /home/tsiegert/miniconda2/envs/threeML/lib/python2.7/site-packages/threeML/data/threeML_config.yml. You might want to copy it to /home/tsiegert/.threeML/threeML_config.yml to customize it and avoid this warning.



In [2]:
spi_pointing = SPIPointing(sc_pointing_file='sc_orbit_param.fits.gz')
sc_point = spi_pointing.sc_matrix[0]
scp = spi_pointing.sc_points[0]

In [3]:
maf = fits.open('inst_misalign_20050328.fits')

mam = np.reshape(maf[1].data[2]['matrix'],[3,3])

In [4]:
print('Misalignment matrix')
print(mam)

Misalignment matrix
[[ 9.99997136e-01  2.65497922e-04 -2.37837002e-03]
 [-2.69012020e-04  9.99998873e-01 -1.47732581e-03]
 [ 2.37797511e-03  1.47796139e-03  9.99996080e-01]]


In [5]:
print('space craft xyz before')
print(sc_point)

print('space craft radec_xyz before')
scp

space craft xyz before
[[-0.57041035 -0.28013682  0.772111  ]
 [ 0.35096277  0.76677282  0.53747984]
 [-0.74260155  0.57756631 -0.33905765]]
space craft radec_xyz before


{'scx_dec': 50.5438346862793,
 'scx_ra': 206.1563262939453,
 'scy_dec': 32.51224513331057,
 'scy_ra': 65.40575996001127,
 'scz_dec': -19.81947135925293,
 'scz_ra': 142.12562561035156}

In [6]:
sc_point_new = np.dot(mam,sc_point)

In [7]:
print('space craft xyz after')
print(sc_point_new)
print('space craft radec_xyz after')

scp_new = np.zeros((3,2))

scp_new[0] = np.array([360,0]) + cart2polar(sc_point_new[0])
scp_new[1] = cart2polar(sc_point_new[1])
scp_new[2] = cart2polar(sc_point_new[2])

#scp_new[0,:] = cart2polar(sc_point_new[0])

print('calculated frame with misalignment matrix')
scp_new

space craft xyz after
[[-0.56854936 -0.28130611  0.77305789]
 [ 0.35221288  0.76599406  0.53777243]
 [-0.74343635  0.57803115 -0.33642588]]
space craft radec_xyz after
calculated frame with misalignment matrix


array([[206.32522477,  50.62928435],
       [ 65.30648408,  32.53212683],
       [142.13448347, -19.65926861]])

In [11]:
print('"true" frame from spimodfit output (probably rounded)')
scp_true = np.array([[206.32600,50.629800],[65.306800,32.531700],[142.13500,-19.659100]])
scp_true

"true" frame from spimodfit output (probably rounded)


array([[206.326 ,  50.6298],
       [ 65.3068,  32.5317],
       [142.135 , -19.6591]])

In [12]:
print('relative uncertainty in values: ')
(scp_new-scp_true)/scp_true

relative uncertainty in values: 


array([[-3.75732797e-06, -1.01847137e-05],
       [-4.83740061e-06,  1.31204163e-05],
       [-3.63406208e-06,  8.57661889e-06]])

In [13]:
print('You definitely must mean spectra, bitch.')

You definitely must mean spectra, bitch.
