In [1]:
# Scientific libraries
import numpy as np

%matplotlib notebook
import matplotlib.pyplot as plt

import astropy.units as u
from astropy.coordinates import ICRS, Galactic, SkyCoord

from pyspi.spi_pointing import SPIPointing
from pyspi.spi_frame import SPIFrame

/Users/jburgess/.environs/3ml/lib/python2.7/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


Configuration read from /Users/jburgess/.threeML/threeML_config.yml


In [2]:
spi_pointing = SPIPointing(sc_pointing_file='sc_orbit_param.fits.gz')

In [3]:
spi_pointing.sc_matrix[0]

array([[-0.57041035, -0.28013682,  0.772111  ],
       [ 0.35096277,  0.76677282,  0.53747984],
       [-0.74260155,  0.57756631, -0.33905765]])

In [3]:
spi_pointing.sc_matrix[0]

array([[-0.56854936, -0.28130611,  0.77305789],
       [ 0.35221288,  0.76599406,  0.53777243],
       [-0.74343635,  0.57803115, -0.33642588]])

In [4]:
scp = spi_pointing.sc_points[0]

In [5]:
spi_frame = SPIFrame(lat=0*u.deg,lon=0*u.deg,**scp)
spi_frame

<SPIFrame Coordinate (scx_ra=206.32522476554993, scx_dec=50.62928434998366, scy_ra=65.30648408484562, scy_dec=32.53212682944631, scz_ra=142.13448347258623, scz_dec=-19.65926860860834): (lon, lat) in deg
    (0., 0.)>

In [5]:
spi_frame = SPIFrame(lat=0*u.deg,lon=0*u.deg,**scp)
spi_frame

<SPIFrame Coordinate (scx_ra=206.1563262939453, scx_dec=50.5438346862793, scy_ra=65.40575996001127, scy_dec=32.51224513331057, scz_ra=142.12562561035156, scz_dec=-19.81947135925293): (lon, lat) in deg
    (0., 0.)>

In [12]:
spi_frame.transform_to(ICRS)

<ICRS Coordinate: (ra, dec) in deg
    (206.32522477, 50.62928435)>

In [7]:
spi_frame.transform_to(Galactic)

<Galactic Coordinate: (l, b) in deg
    (102.97162249, 64.36030988)>

In [8]:
spi_frame.cartesian

<CartesianRepresentation (x, y, z) [dimensionless]
    (1., 0., 0.)>

In [13]:

source = SkyCoord(ra=197.075, dec=58.98,unit='deg',frame='icrs')
center = SkyCoord(ra=206.32522477, dec= 50.62928435, unit='deg', frame='icrs')

source.separation(center).value



9.887579759796989

In [14]:
source_spi = source.transform_to(spi_frame)

center_spi = center.transform_to(spi_frame)

In [15]:
spi_frame.separation(source_spi).value

9.887580143993551

In [21]:
source_spi.cartesian.xyz.value

array([ 0.98507493,  0.17169734, -0.01214088])

In [23]:
from pyspi import SPIResponse
spi = SPIResponse()

In [19]:
source_spi

<SkyCoord (SPIFrame: scx_ra=206.32522476554993, scx_dec=50.62928434998366, scy_ra=65.30648408484562, scy_dec=32.53212682944631, scz_ra=142.13448347258623, scz_dec=-19.65926860860834): (lon, lat) in deg
    (9.87259526, -0.54687267)>

In [25]:
xy = spi.get_xy_pos(np.deg2rad(9.88725697), np.deg2rad(-0.69563811))

In [26]:
xy

(45.629387654172405, 46.761103960262076)

In [18]:
spi_pointing.sc_points

[{'scx_dec': 50.62928434998366,
  'scx_ra': 206.32522476554993,
  'scy_dec': 32.53212682944631,
  'scy_ra': 65.30648408484562,
  'scz_dec': -19.65926860860834,
  'scz_ra': 142.13448347258623},
 {'scx_dec': 50.62928434998366,
  'scx_ra': 206.32522476554993,
  'scy_dec': 32.53212682944631,
  'scy_ra': 65.30648408484562,
  'scz_dec': -19.65926860860834,
  'scz_ra': 142.13448347258623},
 {'scx_dec': 50.62928434998366,
  'scx_ra': 206.32522476554993,
  'scy_dec': 32.53212682944631,
  'scy_ra': 65.30648408484562,
  'scz_dec': -19.65926860860834,
  'scz_ra': 142.13448347258623},
 {'scx_dec': 50.62928434998366,
  'scx_ra': 206.32522476554993,
  'scy_dec': 32.53212682944631,
  'scy_ra': 65.30648408484562,
  'scz_dec': -19.65926860860834,
  'scz_ra': 142.13448347258623},
 {'scx_dec': 50.62978415437832,
  'scx_ra': 206.325684140497,
  'scy_dec': 32.531707791283644,
  'scy_ra': 65.30682581387076,
  'scz_dec': -19.65907591233234,
  'scz_ra': 142.13518386553818},
 {'scx_dec': 50.62978415437832,
  's